name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Export AWS credentials
    - name: Configure AWS Credentials
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        echo "AWS credentials configured."

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Plan Terraform deployment
    - name: Terraform Plan
      run: terraform plan

    # Apply Terraform deployment
    - name: Terraform Apply
      run: terraform apply -auto-approve
